version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cpdaemon"
    schedule: { interval: "weekly" }
  - package-ecosystem: "gomod"
    directory: "/cpctl"
    schedule: { interval: "weekly" }
  - package-ecosystem: "gomod"
    directory: "/cpgolib"
    schedule: { interval: "weekly" }
  - package-ecosystem: "gomod"
    directory: "/build"
    schedule: { interval: "weekly" }
  - package-ecosystem: "gomod"
    directory: "/cptools/dockerpid"
    schedule: { interval: "weekly" }
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
