// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package asm

import (
	"context"
)

// Injectors from wire.go:

func InitServer(ctx context.Context, ins *Instance) (ServerEps, func(), error) {
	mux, err := GetMux(ins)
	if err != nil {
		return ServerEps{}, nil, err
	}
	serverEps, err := NewServerEps(mux)
	if err != nil {
		return ServerEps{}, nil, err
	}
	return serverEps, func() {
	}, nil
}
