// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package asm

import (
	"context"
)

// Injectors from wire.go:

func InitServer(ctx context.Context, ins *Instance) (ServerEps, func(), error) {
	mux, err := GetMux(ins)
	if err != nil {
		return ServerEps{}, nil, err
	}
	viper := ins.Vp
	httpClient, err := NewCpmClient(viper)
	if err != nil {
		return ServerEps{}, nil, err
	}
	agentManager := NewCpmAgentMgr(viper)
	syncer, err := NewCpmSyncer(ins, viper, httpClient, agentManager)
	if err != nil {
		return ServerEps{}, nil, err
	}
	serverEps, err := NewServerEps(mux, syncer)
	if err != nil {
		return ServerEps{}, nil, err
	}
	return serverEps, func() {
	}, nil
}
