/**
* Netis Agent REST APIs
* Netis Agent 管理平台由 **Agent**, **Daemon**, **Manager** 三个组件组成。   * Agent: 部署在用户环境中采集数据，当前支持 Packet Agent 采集网络数据   * Daemon: 部署在用户环境中通过 REST APIs 管理 Agent   * Manager: 部署在监控环境中通过 REST APIs 管理 Daemon 和 Agent 
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * NetworkInterface.h
 *
 * 网卡资源
 */

#ifndef Label_H_
#define Label_H_


#include "ModelBase.h"

#include <string>
#include <vector>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 网卡资源
/// </summary>
class  Label
    : public ModelBase
{
public:
    Label();
    virtual ~Label();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Label value

    std::string getValue() const;
    void setValue(std::string value);
    bool valueIsSet() const;
    void unsetValue();

protected:

    std::string m_Value;
    bool m_ValueIsSet;
};

}
}
}
}

#endif /* NetworkInterface_H_ */
