/**
* Netis Agent REST APIs
* Netis Agent 管理平台由 **Agent**, **Daemon**, **Manager** 三个组件组成。   * Agent: 部署在用户环境中采集数据，当前支持 Packet Agent 采集网络数据   * Daemon: 部署在用户环境中通过 REST APIs 管理 Agent   * Manager: 部署在监控环境中通过 REST APIs 管理 Daemon 和 Agent 
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * Report.h
 *
 * Report 资源
 */

#ifndef Report_H_
#define Report_H_

#include <string>
#include <boost/date_time/posix_time/posix_time.hpp>

#include "ModelBase.h"
#include "PacketAgentLogs.h"
#include "PacketChannelMetrics.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// Report 资源
/// </summary>
class  Report
    : public ModelBase
{
public:
    Report();
    virtual ~Report();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Agent members

    /// <summary>
   
    std::shared_ptr<PacketAgentMetrics> getPacketAgentMetrics() const;

    void setPacketAgentMetrics(std::shared_ptr<PacketAgentMetrics> value);

    bool packetAgentMetricsIsSet() const;

    void unsetPacketAgentMetrics();

    void setPid(int32_t value) {m_Pid = value; m_PidIsSet = true;};

    bool pidIsSet() const {return m_PidIsSet;};

    void unsetPid() {m_PidIsSet = false;};

    void addPacketAgentLogs(const std::string& level, const std::string& details);
    bool packetAgentLogsIsSet() const;
    void unsetPacketAgentLogs();

protected:
    std::vector<std::shared_ptr<PacketAgentLogs>> m_Logs;
    bool m_LogsIsSet;
    std::shared_ptr<PacketAgentMetrics> m_Metrics;
    bool m_MetricsIsSet;
    int32_t m_Pid;
    bool m_PidIsSet;
};

}
}
}
}

#endif /* Agent_H_ */
